# Generated by Django 2.2 on 2020-10-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='PropertyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('services', models.CharField(max_length=500)),
                ('maxPax', models.IntegerField()),
                ('dailyRate', models.IntegerField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='met3App.City')),
            ],
            options={
                'verbose_name_plural': 'PropertiesUser',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('dateReservation', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('propertyUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='met3App.PropertyUser')),
            ],
        ),
        migrations.CreateModel(
            name='RentalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starDate', models.DateField()),
                ('endDate', models.DateField()),
                ('propertyUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='met3App.PropertyUser')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='met3App.Reservation')),
            ],
            options={
                'verbose_name_plural': 'RentalDates',
            },
        ),
    ]
