# Generated by Django 2.2 on 2020-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met3App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyuser',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propertyuser',
            name='starDate',
            field=models.DateField(),
        ),
    ]
