# Generated by Django 2.2 on 2020-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met3App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.OneToOneField(null=True, on_delete=False, to='auth.Group'),
        ),
    ]
