# Generated by Django 2.2 on 2020-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met3App', '0002_auto_20201028_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.OneToOneField(null=True, on_delete=True, to='auth.Group'),
        ),
    ]
